/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

/**
 *
 * @author Michael
 */
public class LogIn extends javax.swing.JFrame
{

	/**
	 * Creates new form LogIn
	 */
	public LogIn()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    tfLogUsername = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    tfLogPassword = new javax.swing.JTextField();
    jPanel4 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    tfRegUsername = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    tfRegPassword = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    tfRegPasswordCheck = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    tfRegEMail = new javax.swing.JTextField();
    jPanel6 = new javax.swing.JPanel();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

    jPanel1.setLayout(new java.awt.BorderLayout());

    jPanel3.setLayout(new java.awt.GridLayout(0, 2));

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel1.setText(" Username: ");
    jPanel3.add(jLabel1);

    tfLogUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jPanel3.add(tfLogUsername);

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel2.setText(" Password: ");
    jPanel3.add(jLabel2);

    tfLogPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jPanel3.add(tfLogPassword);

    jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

    jPanel4.setLayout(new java.awt.GridLayout(1, 0));

    jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButton1.setText("LogIn");
    jPanel4.add(jButton1);

    jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButton2.setText("Cancel");
    jPanel4.add(jButton2);

    jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

    jTabbedPane1.addTab("LogIn", jPanel1);

    jPanel2.setLayout(new java.awt.BorderLayout());

    jPanel5.setLayout(new java.awt.GridLayout(0, 2));

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel3.setText(" Username: ");
    jPanel5.add(jLabel3);

    tfRegUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jPanel5.add(tfRegUsername);

    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel4.setText(" Password: ");
    jPanel5.add(jLabel4);

    tfRegPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jPanel5.add(tfRegPassword);

    jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel5.setText(" Password check:");
    jPanel5.add(jLabel5);

    tfRegPasswordCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jPanel5.add(tfRegPasswordCheck);

    jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel6.setText(" E-Mail-Address: ");
    jPanel5.add(jLabel6);

    tfRegEMail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jPanel5.add(tfRegEMail);

    jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

    jPanel6.setLayout(new java.awt.GridLayout(1, 0));

    jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButton3.setText("Register");
    jPanel6.add(jButton3);

    jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButton4.setText("Cancel");
    jPanel6.add(jButton4);

    jPanel2.add(jPanel6, java.awt.BorderLayout.SOUTH);

    jTabbedPane1.addTab("Register", jPanel2);

    getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new LogIn().setVisible(true);
			}
		});
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JTextField tfLogPassword;
  private javax.swing.JTextField tfLogUsername;
  private javax.swing.JTextField tfRegEMail;
  private javax.swing.JTextField tfRegPassword;
  private javax.swing.JTextField tfRegPasswordCheck;
  private javax.swing.JTextField tfRegUsername;
  // End of variables declaration//GEN-END:variables
}
